### ISSUE TITLE
Aika hauskat tehtävät 2. osassa....

### ISSUE THREAD

**Issue by ivose** [centria/coding-exercises#1]
Aika hauskat tehtävät 2. osassa.... . Pistää vain helloworldeja...
![image](https://user-images.githubusercontent.com/1102852/117660724-306bf100-b1a6-11eb-8643-ed98045f3d50.png)

**Comment by HeikkiHei** [comment]
Nuo tehtävät ovat eri kurssilta, joka ei ole vielä julkaistu. Suljen issuen.
